### ISSUE TITLE
Auto-select components across workloads

### ISSUE THREAD

**Issue by odalet** [willnode/Vs2017-LayoutInGUI#1]
I'm wondering: wouldn't it be better to select identical components across workloads?
Say I checked the MSBuild component inside ".NET desktop development", shouldn't it automatically be checked as well in "ASP.NET and web development" or any other workload that declares it?

Conversely, should deselecting a component from any workload imply it is removed from all workloads?

**Comment by willnode** [comment]
@odalet you're right. Each component that gets manually selected are always get included. If two identical component get checked, then two identical component also get included in `--add` parameter. 

I suspect this would not generate problem in VS side. Albeit I should add conditional to check redundant `--add`.

> Say I checked the MSBuild component inside ".NET desktop development", shouldn't it automatically be checked as well in "ASP.NET and web development" or any other workload that declares it?

I agree with this, but I fear this will be technically difficult to implement, for such simple behaviour.

**Comment by willnode** [comment]
I've fixed the duplicate problem in component args. I think this should be enough.
