### ISSUE TITLE
Crash when fetch layout info on 2018-08-31

### ISSUE THREAD

**Issue by isral** [willnode/Vs2017-LayoutInGUI#3]
On 2018-08-31 both v12 and v13 crash when fetching layout info.
No error message. The window just suddenly closed.

Edit: I found the culprit. I just create an issue there.
https://github.com/MicrosoftDocs/visualstudio-docs/issues/1464

**Comment by willnode** [comment]
Thanks for the report. I just commited a fix for that.

There should be some additional code to properly handle this kind of situation. I'll address that before getting a new version released.
